version: "3"

services:
  mongo:
    image: mongo
    restart: always
    ports: 
      - 8089:8089
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: fullstack
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
